### PR TITLE
Added ecomode to set_device

### PR DESCRIPTION
**Pull request by djbulsink**
Setting the ecomode didn't work. This PR implements the Ecomode in the set_device method.

### CODE REVIEW

**Comment by anthonymf** [comment]
@djbulsink The only thing left is to set the missing arg [here](https://github.com/lostfields/python-panasonic-comfort-cloud/blob/dc17e37/pcomfortcloud/__main__.py#L207) like this
```
            if args.eco is not None:
                kwargs['eco'] = pcomfortcloud.constants.EcoMode[args.eco]
```
And then it works like a (Quiet) dream! 😄 

Let me know if you want a PR (here or on the fork?)

**Comment by lostfields** [comment]
Thanks for the PR, but we have to do a little more. Take a look at issue #1 

The RAW dump often says that econavi and nanoe isn't supported, but it still is. The first time we have to list out supported modes for econavi and nanoe - and I have found out it is supported if the parameter is >= 1. 

0 = unsupported (then we never ever set this property)
1 = off
2 = on

**Comment by inforsgit** [comment]
> Thanks for the PR, but we have to do a little more. Take a look at issue #1
> 
> The RAW dump often says that econavi and nanoe isn't supported, but it still is. The first time we have to list out supported modes for econavi and nanoe - and I have found out it is supported if the parameter is >= 1.
> 
> 0 = unsupported (then we never ever set this property)
> 1 = off
> 2 = on

Actually this is different to issue #1 - that refers to adding support for econavi/Nanoe. This is just the "ecomode" of the device (Auto/Quiet/Powerful) which is already implemented in python-panasonic-comfort-cloud but the set method doesn't work (only the read). This should fix it.

**Comment by lostfields** [comment]
oh, sorry, my mistake :-)

**Pull request merged**
